owner: helllth
repo: upptime
user-agent: cismet-uptime-bot
#i18n: i18n.yml
sites:
  - name: Bebauungspläne Wuppertal
    url: https://www.wuppertal.de/wirtschaft-stadtentwicklung/planverfahren/bebauungsplaene.php
  - name: Dokumentenansicht 1229
    url: https://wuppertal.planoffenlegung.de/#/docs/bplaene/1229/1/1
  - name: PDF 1229
    url: https://wunda-geoportal-docs.cismet.de//bplaene/verfahren/B1229.pdf
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - helllth
status-website:
  #cname: upptime.js.org
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: Upptime Entwicklungsinstanz der cismet GmbH
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Dies ist eine Beispiel-Statusseite, die **Echtzeit**-Daten aus unserem [Github-Repository] (https://github.com/cismet/uptime-dev) verwendet. 
